# Mandrill environment variables

SMTP_PORT: 587
SMTP_HOST: "smtp.mandrillapp.com"
SMTP_USERNAME: "akrueger"
SMTP_PASSWORD: "tfx_9NyyJLzZhlQSOliuSw"
SMTP_PASSWORD_PROD: "KTW6PzfThOBovFNX6DmZcw"

# Wolfram API environment variables

WOLFRAM_APPID: "U2T3J4-AU3R62W62A"