SMTP_PORT: 587
SMTP_HOST: "smtp.mandrillapp.com"
SMTP_USERNAME: "akrueger"
SMTP_PASSWORD: "tfx_9NyyJLzZhlQSOliuSw"
SMTP_PASSWORD_PROD: "KTW6PzfThOBovFNX6DmZcw"

FORECAST_IO_KEY: "23247cd984195ff93b782688e0639f12"